server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configtree:/run/secrets/

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_AUTH_USER}
    password: ${DB_AUTH_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  keys:
    private: ${JWT_PRIVATE_KEY}
    public: ${JWT_PUBLIC_KEY}
  ttl:
    access-token: 15m
    refresh-token: 7d
  key-id: ${AUTH_KEY_ID}