spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:55432/auth_db
    username: auth_user
    password: auth_password

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  keys:
    private: keys/private.pem
    public: keys/public.pem